### ISSUE TITLE
Traefik plugin "Internal Server Error" on cache expire

### ISSUE THREAD

**Issue by lansaloni** [darkweak/souin#157]
Hi,
I setup traefik in docker swarm as follow:

```
version: "3.8"
services:
  traefik:
    image: traefik:v2.5.0
    command:
      - "--api.insecure=true"
      - "--log=true"
      - "--log.filepath=/traefik.log"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.docker.httpClientTimeout=0"
      - "--providers.file.directory=/conf"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.forwardedHeaders.insecure"
      - "--certificatesresolvers.myresolver.acme.email=MY-EMAIL"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
      - "--pilot.token=d1f81388-a695-4332-9f21-824d234068c0"
      - "--experimental.plugins.souin.modulename=github.com/darkweak/souin"
      - "--experimental.plugins.souin.version=v1.5.10"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /swarm/volumes/traefik/cache:/cache/
      - /swarm/volumes/traefik/conf:/conf/
      - /swarm/volumes/traefik/acme:/acme/
      - /swarm/volumes/traefik/traefik.log:/traefik.log
      - /swarm/volumes/traefik/etc/certs:/etc/certs/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
      - target: 8080
        published: 8081
          
          
networks:
  proxy:
    driver: overlay
    external: true
```

I use the file _conf/cache-http.yaml_ to configure souin plugin as follow:
```
http:
  middlewares:
    cache-http:
      plugin:
        souin:
          log_level: debug
          default_cache:
            headers:
              - Authorization
              - Content-Type
            ttl: 30s
```

this is the stack behind the proxy:

```
  dsm-nginx-php80:
    image: gcr.io/docker-registry-259114/ubuntu2004-nginx-php80:latest
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 40s
    depends_on:
      - mysql
    environment:
      - SMTP_MAILNAME=dsm-nginx-php80
      - SMTP_USERNAME=server-ext@newlogic.it
      - SMTP_PASSWORD=nwl01serv
    volumes:
      - /swarm/volumes/dsm-nginx-php80/var/www:/var/www
      - /swarm/volumes/dsm-nginx-php80/usr/local/bin:/usr/local/bin
      - /swarm/volumes/dsm-nginx-php80/var/spool/cron/crontabs:/var/spool/cron/crontabs
      - /swarm/volumes/xdebug/tmp:/xdebug/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /swarm/volumes/dsm-nginx-php80/etc/nginx:/etc/nginx
      - /swarm/volumes/dsm-nginx-php80/etc/php:/etc/php
      - /swarm/volumes/dsm-nginx-php80/var/log:/var/log
      - /swarm/volumes/dsm-nginx-php80/home/root:/root
    networks:
      - dsm-net
      - proxy
    ports:
      - "2224:22"
    domainname: modular.lan
    hostname: dsm-nginx-php80
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.services.dsm-nginx-php80.loadbalancer.server.port=80"
        - "traefik.http.services.dsm-nginx-php80.loadbalancer.healthcheck.hostname=dsm-nginx-php80"
        - "traefik.http.services.dsm-nginx-php80.loadbalancer.healthcheck.interval=100ms"
        - "traefik.http.services.dsm-nginx-php80.loadbalancer.healthcheck.timeout=75ms"
        - "traefik.http.services.dsm-nginx-php80.loadbalancer.healthcheck.scheme=http"
        - "traefik.http.services.dsm-nginx-php80.loadbalancer.healthcheck.port=80"
        - "traefik.http.services.dsm-nginx-php80.loadbalancer.sticky.cookie=false"
        - "traefik.http.routers.dsm-nginx-php80-00-http.entrypoints=http"
        - "traefik.http.routers.dsm-nginx-php80-00-http.middlewares=cache-http@file"
        - "traefik.http.routers.dsm-nginx-php80-00-http.rule=Host(`dsm-nginx-php80.MY-DOMAIN`)"
        - "traefik.http.routers.dsm-nginx-php80-00-http.tls=false"
        - "traefik.http.routers.dsm-nginx-php80-00-https.entrypoints=https"
        - "traefik.http.routers.dsm-nginx-php80-00-https.middlewares=cache-http@file"
        - "traefik.http.routers.dsm-nginx-php80-00-https.rule=Host(`dsm-nginx-php80.MY-DOMAIN`)"
        - "traefik.http.routers.dsm-nginx-php80-00-https.tls=true"


networks:
  proxy:
    external: true
```

I load 2 simple files for testin into the web root:
_index.html_
```
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="styles.css">
  </head>
  <body>

  <h1>This is a heading</h1>
  <p>This is a paragraph.</p>

</body>
</html>
```
_styles.css_
```
body {
  background-color: powderblue;
}
h1 {
  color: blue;
}
p {
  color: red;
}
```

when I load the page for the first time I get a _cache miss_:
![cache_miss](https://user-images.githubusercontent.com/46852698/143910583-3a74c558-3ec5-4696-aacb-7cf2da3a5f95.png)

the second time I get a _chache hit_:
![cache_hit](https://user-images.githubusercontent.com/46852698/143910745-65b01272-9fd2-4340-85e8-7e7f7540022e.png)

but when the cache expire and i reload the page I get an _internal server error_:
![internal_server_error](https://user-images.githubusercontent.com/46852698/143910847-547cb7a6-533a-4897-9a6d-0031052f4497.png)

and _traefik_ log this error:
```
plugins-storage/sources/gop-1860359802/src/github.com/darkweak/souin/plugins/traefik/vendor/github.com/darkweak/souin/rfc/standalone.go:335:11: panic,
plugins-storage/sources/gop-1860359802/src/github.com/darkweak/souin/plugins/traefik/base.go:62:10: panic,
plugins-storage/sources/gop-1860359802/src/github.com/darkweak/souin/plugins/traefik/main.go:209:10: panic,
plugins-storage/sources/gop-1860359802/src/github.com/darkweak/souin/plugins/traefik/base.go:107:14: panic,
plugins-storage/sources/gop-1860359802/src/github.com/darkweak/souin/plugins/traefik/main.go:162:94: panic
```

did I do something wrong?
Bye,
Lorenzo
