### ISSUE TITLE
TraefikEE 2.5.3 installation error (plugins not found)

### ISSUE THREAD

**Issue by 917huB** [darkweak/souin#163]
Trying to add this to my static config, I get the following error when trying to deploy static.yaml
```
root@traefik-ctl:/opt/traefikee# teectl apply --file="static.yaml"
teectl encountered an error: command apply error: unable to apply static configuration: unable to apply new configuration: rpc error: code = Internal desc = unable to apply new configuration: invalid plugins: plugins not found: github.com/darkweak/souin@v1.5.11-beta6
```

section from static.yaml
```
...
experimental:
  plugins:
    souin:
      moduleName: github.com/darkweak/souin
      version: v1.5.11-beta6
...
```

sorry if this is a newb error. It seems pretty fundamental and my other plugins work fine.
