### ISSUE TITLE
[question] Upstreams as cache key

### ISSUE THREAD

**Issue by mattvb91** [darkweak/souin#219]
I feel like this is the right place to ask this,

Im wondering is it possible to deduplicate alot of cache entries based on the upstream that an asset is being served from?
For example I could have 100s of domains but the frontend is all being served from the exact same nextjs upstream.

However in the cache key list I get the following:

```json
[
"GET-host1.localhost-/_next/my-css.css",
"GET-host2.localhost-/_next/my-css.css",
"GET-host3.localhost-/_next/my-css.css",
"GET-host4.localhost-/_next/my-css.css",
"GET-host5.localhost-/_next/my-css.css",
"GET-host6.localhost-/_next/my-css.css",
... etc
]
```

Im assuming souin actually keeps seperate assets in memory for each host or does it realize its the exact same one and just points to it?

Is it possible to do something like:

```json
[
   "handler": "cache",
   "use_upstream_key_prefix": true
]
```

Which would then result in just 1 cache entry instead of hundreds:

```json
[
"GET-nextjs-/_next/my-css.css",
]
```

I wonder would that help reduce the memory footprint of the overall cache when serving the exact same assets across multiple domains? 

I think the `urls` regex config `surrogate_keys.{key name}.url` option may be what im looking for?

```yml
urls:
  '/.\.css$/':  //Something like that?
```

**Comment by darkweak** [comment]
Hello @mattvb91, 
First, the surrogate_keys are not equal to the cache key. A cache key is the key to retrieve a stored data. The surrogate_keys are the keys to group some cache keys, like ykeys in varnish.
I'll need to rewrite some part of the code.
With that I should be able to propose a configuration like

```yaml
cache_keys:
  '{valid_url_regex}':
      disable_body: true
      disable_domain: true
      disable_method: true
```

And could generate the following url
`{method+'-'}{host+'-'}{request_uri}{hash_request_body}`

```yaml
# Example
cache_keys:
  '\.css$':
      disable_body: true
      disable_domain: true
      disable_method: true
```
With this configuration we could have `/my_asset.css` and all domains could serve the same my_asset.css

```yaml
# Example
cache_keys:
  '(host1|host2)\/.+\.css$':
      disable_body: true
      disable_domain: true
      disable_method: true
```
With this configuration we could have `/my_asset.css` for `host1` and `host2` and keep `GET-host[X]-/my_asset.css`.

WDYT about that?
