### ISSUE TITLE
Configure cache provider for file storage with traefik plugin

### ISSUE THREAD

**Issue by igoooor** [darkweak/souin#227]
Hi,

I am trying to have my cache stored in a directory instead of in memory for traefik plugin.
Here is my middleware:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cache
  namespace: default
spec:
  plugin:
    souin-cache-plugin:
      default_cache:
        nuts:
          configuration:
            path: /tmp/cache
        ttl: 60s
```

The cache `hit` but I don't see files in `/tmp/cache`.
I also tried this alternative configuration:
```
nuts:
  path: /tmp/cache
```
But same results.

Am I missing something?
Thanks in advance for any help
