### ISSUE TITLE
uri-miss on basic traefik middleware config

### ISSUE THREAD

**Issue by tfyl** [darkweak/souin#263]
I was trying to get a basic version of souin working on a traefik config (running from a k8s CRD config)
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-cache
  namespace: services
spec:
  plugin:
    souin:
      default_cache:
        ttl: 120s
      log_level: debug
```
also used the aforementioned middleware on a specified route and enabled the plug-in using the args:
```sh
   --experimental.plugins.souin.modulename=github.com/darkweak/souin
   --experimental.plugins.souin.version=v1.6.22
  ```

I can see that the souin middleware is being called due to `Cache-Status: Souin; fwd=uri-miss` being included in the response header. However after the initial GET request, my understanding is they should be cached from then on (for 120s), instead, requests seem to continue hitting the origin server (container) and return `Cache-Status: Souin; fwd=uri-miss`.

I have attempted adding other optional parameters but to no avail. Is there something I am missing in the config which is causing the `uri-miss` as I cannot seem to get any response which is retrieved from cache?

Thank you in advance.

**Comment by darkweak** [comment]
Hello @tfyl can you paste the request with the headers and the response with the headers too?

**Comment by darkweak** [comment]
Hello @VladyslavLukyanenko 
Can you try without a k8s environment?
What's your træfik version?

That's weird because on the E2E tests everything is working, the headers are present and the response is stored.

**Comment by darkweak** [comment]
That's just to check if that's a Træfik version issue, k8s one or in the cache middleware itself. Because of they use Yægi as interpreter and they make some BC without notices we have to try these use cases.
Anyway, I'll investigate on that and keep you updated.

**Comment by darkweak** [comment]
I cannot reproduce on a docker-compose stack
```
version: '3'

services:
  traefik:
    image: traefik:v2.9.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GOPATH: /plugins-local
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --experimental.plugins.souin.modulename=github.com/darkweak/souin
      - --experimental.plugins.souin.version=v1.6.22
      - --providers.docker=true
      - --entrypoints.https.address=:443
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  whoami:
    image: traefik/whoami
    labels:
      - traefik.http.routers.whoami.rule=Host(`domain.com`)
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.middlewares=souin
      - traefik.http.middlewares.souin.plugin.souin.default_cache.ttl=120s
      - traefik.http.middlewares.souin.plugin.souin.log_level=debug
```
Can you check that you don't add a `Cache-Control: no-cache` header?
