### ISSUE TITLE
[TRAEFIK] Using default config for endpoints panics

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [darkweak/souin#264]
if I use this config:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-cache
  namespace: services
spec:
  plugin:
    souin:
      api:
        basepath: /souin-api # Default route basepath for every additional APIs to avoid conflicts with existing routes
        prometheus: # Prometheus exposed metrics
          basepath: /anything-for-prometheus-metrics # Change the prometheus endpoint basepath
        souin: # Souin listing keys and cache management
          basepath: /anything-for-souin # Change the souin endpoint basepath
      default_cache:
        ttl: 120s
      log_level: debug
```
We get this error upon loading:
```
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-storage/sources/gop-4162997968/src/github.com/darkweak/souin/plugins/traefik/main.go:40:19: panic","plugin":"plugin-souin","time":"2022-10-20T09:23:41Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-storage/sources/gop-4162997968/src/github.com/darkweak/souin/plugins/traefik/main.go:212:3: panic","plugin":"plugin-souin","time":"2022-10-20T09:23:41Z"}
{"level":"error","msg":"Error in Go routine: interface conversion: interface {} is map[string]interface {}, not string","time":"2022-10-20T09:23:41Z"}
{"level":"error","msg":"Stack: goroutine 79 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x30bcb40?, 0xc003a5a680})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x36\npanic({0x30bcb40, 0xc003a5a680})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.14.2/interp/run.go:192 +0x148\npanic({0x30bcb40, 0xc003a5a680})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.14.2/interp/run.go:192 +0x148\npanic({0x30bcb40, 0xc003a5a680})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.typeAssert.func3(0xc0030e0420)\n\tgithub.com/traefik/yaegi@v0.14.2/interp/run.go:440 +0x5c5\ngithub.com/traefik/yaegi/interp.runCfg(0xc004796480, 0xc0030e0420, 0xc005336388?, 0x3281f00?)\n\tgithub.com/traefik/yaegi@v0.14.2/interp/run.go:200 +0x29d\ngithub.com/traefik/yaegi/interp.call.func9(0xc0030e0370)\n\tgithub.com/traefik/yaegi@v0.14.2/interp/run.go:1438 +0x965\ngithub.com/traefik/yaegi/interp.runCfg(0xc0047d8900, 0xc0030e0370, 0x39?, 0x30bcb40?)\n\tgithub.com/traefik/yaegi@v0.14.2/interp/run.go:200 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0xc0040be540, 0x4, 0x8?})\n\tgithub.com/traefik/yaegi@v0.14.2/interp/run.go:1022 +0x487\nreflect.Value.call({0xc00498a980?, 0xc0049906c0?, 0x7f51f8ff25b8?}, {0x39e926c, 0x4}, {0xc0053373d0, 0x4, 0xc00218a590?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xc00498a980?, 0xc0049906c0?, 0xc00469f9e0?}, {0xc0053373d0?, 0xc0007857d0?, 0x0?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/traefik/v2/pkg/plugins.middlewareBuilder.newHandler({{0xc00498a980, 0xc0049906c0, 0x13}, {0xc00497ef00, 0xc004990990, 0x13}}, {0x44bf310?, 0xc00469f980?}, {0x44953c0, 0xc00469f950}, ...)\n\tgithub.com/traefik/traefik/v2/pkg/plugins/middlewares.go:62 +0x345\ngithub.com/traefik/traefik/v2/pkg/plugins.(*Middleware).NewHandler(0x5?, {0x44bf310?, 0xc00469f980?}, {0x44953c0?, 0xc00469f950?})\n\tgithub.com/traefik/traefik/v2/pkg/plugins/middlewares.go:132 +0x115\ngithub.com/traefik/traefik/v2/pkg/server/middleware.(*Builder).buildConstructor.func23({0x44953c0?, 0xc00469f950?})\n\tgithub.com/traefik/traefik/v2/pkg/server/middleware/middlewares.go:360 +0x3c\ngithub.com/traefik/traefik/v2/pkg/middlewares/tracing.Wrap.func1({0x44953c0?, 0xc00469f950?})\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/tracing/wrapper.go:24 +0x5a\ngithub.com/traefik/traefik/v2/pkg/server/middleware.(*Builder).BuildChain.func1({0x44953c0, 0xc00469f950})\n\tgithub.com/traefik/traefik/v2/pkg/server/middleware/middlewares.go:81 +0xf7\ngithub.com/containous/alice.Chain.Then({{0xc001ffddc0?, 0xc001ffddd8?, 0xc00469f0b0?}}, {0x44950e0?, 0xc003767890?})\n\tgithub.com/containous/alice@v0.0.0-20181107144136-d83ebdd94cbd/chain.go:51 +0x8f\ngithub.com/traefik/traefik/v2/pkg/server/router.(*Manager).buildHTTPHandler(0xc005337d78, {0x44bf310?, 0xc00469f0b0}, 0xc000c7c410, {0xc003508a00, 0x4a})\n\tgithub.com/traefik/traefik/v2/pkg/server/router/router.go:190 +0x5a5\ngithub.com/traefik/traefik/v2/pkg/server/router.(*Manager).buildRouterHandler(0xc005337d78, {0x44bf310, 0xc00469f0b0}, {0xc003508a00, 0x4a}, 0x0?)\n\tgithub.com/traefik/traefik/v2/pkg/server/router/router.go:144 +0xac\ngithub.com/traefik/traefik/v2/pkg/server/router.(*Manager).buildEntryPointHandler(0x44bf2a0?, {0x44bf310?, 0xc00469ef90}, 0x1?)\n\tgithub.com/traefik/traefik/v2/pkg/server/router/router.go:114 +0x1e5\ngithub.com/traefik/traefik/v2/pkg/server/router.(*Manager).BuildHandlers(0xc005337d78, {0x44bf2a0, 0xc000058028}, {0xc00498ac80?, 0x5, 0x8}, 0x0?)\n\tgithub.com/traefik/traefik/v2/pkg/server/router/router.go:68 +0x258\ngithub.com/traefik/traefik/v2/pkg/server.(*RouterFactory).CreateRouters(0xc0049a3f80, 0xc00455e940)\n\tgithub.com/traefik/traefik/v2/pkg/server/routerfactory.go:78 +0x25b\nmain.switchRouter.func1({0xc0046159b0?, 0xc004ff8240?, 0xc003ded450?, 0xc0046159e0?})\n\tgithub.com/traefik/traefik/v2/cmd/traefik/traefik.go:380 +0x73\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).applyConfigurations(0xc0049a8000, {0x44bf268, 0xc00015b580})\n\tgithub.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:172 +0x21d\ngithub.com/traefik/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:36 +0x66\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x5b\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:53 +0x72\n","time":"2022-10-20T09:23:41Z"}
```

Leaving the CRD as;

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-cache
  namespace: services
spec:
  plugin:
    souin:
      default_cache:
        ttl: 120s
      log_level: debug
```

Removing the api specifications makes it work again normally.
