### ISSUE TITLE
[TRAEFIK] Setting cache_name param has no effect

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [darkweak/souin#265]
Traefik version: 2.9.1

CRD:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-cache
  namespace: services
spec:
  plugin:
    souin:
      default_cache:
        cache_name: CacheService
        ttl: 120s
      log_level: debug
```
Response:
```
HTTP/2 200
access-control-allow-origin: *
cache-status: Souin; fwd=uri-miss
content-type: application/json
date: Thu, 20 Oct 2022 09:54:33 GMT
server: istio-envoy
vary: Origin
x-envoy-upstream-service-time: 22
x-request-id: 23364eaa-75b1-914c-9f35-94a769fb629f
content-length: 289
```
