### ISSUE TITLE
[Traefik Plugin] Setting default_cache.allowed_http_verbs does not seem to work

### ISSUE THREAD

**Issue by jonasengelmann** [darkweak/souin#304]
I was attempting to define the `allowed_http_verbs` for a traefik middleware, but adding `- traefik.http.middlewares.http-cache.plugin.souin.default_cache.allowed_http_verbs=POST` does not seem to have an effect. Is setting http verbs not supported for traefik or is traefik's interpreter misinterpreting things again? 

Here is my test setup:
```
version: "3.8"
services:
  traefik:
    image: traefik:v2.7.0
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --experimental.plugins.souin.moduleName=github.com/darkweak/souin
      - --experimental.plugins.souin.version=v1.6.28
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`localhost`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.middlewares.http-cache.plugin.souin.api.souin
      - traefik.http.middlewares.http-cache.plugin.souin.default_cache.allowed_http_verbs=POST
      - traefik.http.middlewares.http-cache.plugin.souin.log_level=debug
      - traefik.http.routers.whoami.middlewares=http-cache
```

Running `curl -X POST -i http://localhost` returns this header:
```
HTTP/1.1 200 OK
Cache-Status: Souin; fwd=uri-miss; key=; detail=CANNOT-HANDLE
Content-Length: 359
Content-Type: text/plain; charset=utf-8
```

Running `curl -i http://localhost` returns this header:
```
HTTP/1.1 200 OK
Cache-Status: Souin; fwd=uri-miss; stored
Content-Length: 376
Content-Type: text/plain; charset=utf-8
```
