### ISSUE TITLE
question: traefik community or enterprise?

### ISSUE THREAD

**Issue by codeagencybe** [darkweak/souin#339]
Hello

Can this caching be used with the open source Traefik version too or is Enterprise required? 
I checked the information and it says about Traefik Hub for plugins, but the Hub is no longer free. 

Anybody who can shed some light on this? 
I'm trying to simply deploy Wordpress on Kubernetes with Traefik and want to improve the performance with a caching layer, hopefully Souin can help me with this. 

Thanks.

**Comment by darkweak** [comment]
Hello @codeagencybe, obviously it can be used by the Træfik open source version. You don't need Træfik CE to load plugins, you can just load them through the configuration
```yaml
experimental:
  plugins:
    souin:
      moduleName: github.com/darkweak/souin
      version: v1.6.38
```
