### ISSUE TITLE
Cannot hide key in Cache-Status response header

### ISSUE THREAD

**Issue by yongzhang** [darkweak/souin#352]
Hi @darkweak 

I'm testing souin `v1.6.38` with traefik `2.9.10` today, I have config like this:

```
experimental:
  localPlugins:
    caching:
      moduleName: github.com/darkweak/souin
----------------
http:
  middlewares:
    http-cache:
      plugin:
        caching:
          default_cache:
            ttl: 5m
            default_cache_control: no-store
            key:
              disable_body: true
              disable_host: false
              disable_method: false
              disable_query: true
              hide: true
          log_level: debug

  routers:
    whoami-cache:
      entryPoints:
        - "web"
      rule: "Host(`whoami.example.com`) && PathPrefix(`/cache`)"
      service: whoami
      middlewares:
        - http-cache

  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami/"
```

I got:

```
*   Trying 127.0.0.1:8080...
> GET /cache HTTP/1.1
> Host: whoami.example.com
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Age: 1
< Cache-Status: Souin; hit; ttl=299; key=GET-http-whoami.example.com-/cache
< Content-Length: 469
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 14 Jun 2023 06:46:07 GMT
< Vary: Accept-Encoding
```

Caching is working, which is great! But seems like `hide: true` is not working, any ideas?

And are we able to have simple cache status header something like:

```
X-Cache-Status: HIT[MISS|...]
```

Thanks.
