### ISSUE TITLE
One simple, working example

### ISSUE THREAD

**Issue by ribeaud** [Darkweak/Souin#43]
Hi, Currently trying to get a simple working example. I've read the (quite sparse) doc, saw [this](https://stackoverflow.com/questions/65854068/souin-and-traefik-https-bad-gateway) post and went through following [slides](https://slides.com/darkweak/how-do-i-made-a-powerful-cache-system-using-go).

I am using following configuration (the simplest one up to the doc):
```yml
default_cache: # Required part
  port: # Ports to expose Souin
    web: 80
  ttl: 10 # Default TTL
reverse_proxy_url: 'http://localhost'
```
I am running following **Docker Compose** configuration:
```yml
version: '3.7'

services:

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "81:80"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  souin:
    image: darkweak/souin:latest
    ports:
      - 80:80
    depends_on:
      - redis
    environment:
      GOPATH: /app
    volumes:
      - ./configuration.yml:/configuration/configuration.yml

  redis:
    image: redis:alpine
```
Getting following output:
```bash
Attaching to souin_redis_1, simple-service, souin_traefik_1, souin_souin_1
redis_1    | 1:C 21 Mar 2021 03:36:40.289 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 21 Mar 2021 03:36:40.290 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 21 Mar 2021 03:36:40.290 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1    | 1:M 21 Mar 2021 03:36:40.290 * monotonic clock: POSIX clock_gettime
souin_1    | standard_init_linux.go:219: exec user process caused: exec format error
simple-service | Starting up on port 80
traefik_1  | time="2021-03-21T03:36:40Z" level=info msg="Configuration loaded from flags."
redis_1    | 1:M 21 Mar 2021 03:36:40.291 * Running mode=standalone, port=6379.
redis_1    | 1:M 21 Mar 2021 03:36:40.291 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 21 Mar 2021 03:36:40.291 # Server initialized
redis_1    | 1:M 21 Mar 2021 03:36:40.291 * Ready to accept connections
souin_souin_1 exited with code 1
```
So what am I doing wrong? Is this project used at all (googling for **souin** and **traefik** does not return that much help/matches)?

Thanks and have a beautiful day.
