### ISSUE TITLE
souin on traefik get api souin url

### ISSUE THREAD

**Issue by artb1sh** [darkweak/souin#450]
Hi all,
I do not know if I use an incorrect configuration or if api souin simply does not work 

Dynamic conf:
```
    http-cache:
      plugin:
        souin:
          api:
            prometheus: {}
            souin:
              enable: true
```

```
  site-front:
    labels:
    ...........
      - "traefik.http.routers.site-front.middlewares=http-cache@file"
```
curl -I https://site-front/
cache-status: Souin; fwd=uri-miss; stored;
curl -I https://site-front/
cache-status: Souin; hit;

curl https://site-front/souin    <- API souin
404 n
how get api souin url?
