### ISSUE TITLE
[k8s Træfik plugin] invalid middleware type

### ISSUE THREAD

**Issue by peltho** [darkweak/souin#575]
I'm trying to use your plugin on a Kubernetes environment.
To do so, I implemented one middleware (for Træfik dynamic config) this way:
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: souin
spec:
  plugin:
    souin:
      api:
        prometheus: {}
        souin: {}
      default_cache:
        ttl: 5s
      log_level: debug
```
Then I updated my Træfik static config:
```yaml
experimental:
  plugins:
     souin:
       moduleName: github.com/darkweak/souin
       version: v1.7.5
```

Until now everything's ok on Træfik UI, but at the time I reference the middleware for a given service (in its IngressRoute) it fails:

```yaml
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: my-service-ingressroute
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`foo.com`) && !Path("/")
    kind: Rule
    middlewares:
    - name: souin #                    <-- here is the reference
    services:
    - name: my-service
      port: 8080
  tls:
    certResolver: letsencrypt
```

<img width="444" alt="image" src="https://github.com/user-attachments/assets/100bcba5-1a20-4dc9-8b5d-7100003ad56e">

Am I doing something wrong?
