### ISSUE TITLE
Exclude base path but include specific path

### ISSUE THREAD

**Issue by omri-shilton** [darkweak/souin#621]
When trying to exclude a regex with the same base path as some of the `urls` it just excludes everything:
```
api:
  prometheus: {}
  souin: {}
default_cache:
  allowed_http_verbs:
    - GET
    - POST
  default_cache_control: public
  key:
    headers:
      - Authorization
  mode: strict
  exclude: "^/api/.+"
  ttl: 5m
urls:
  /api/auth/verify:
    default_cache_control: public
    key:
      headers:
        - Authorization
    ttl: 5m

```
