### ISSUE TITLE
Duplicate body when using souin as traefik plugin on uri-miss

### ISSUE THREAD

**Issue by omri-shilton** [darkweak/souin#626]
When using souin as a traefik plugin im getting the body duplicated when the cache is `uri-miss`.
In the screenshots below you can see that when i'm requesting directly without traefil im getting content-length of `30364`.
When i'm requesting through traefik without cache im getting `30364`.
When i'm accessing through traefik and cache im getting `60728` (im saving you the trouble of attaching the body, but its a duplicated json).

![Image](https://github.com/user-attachments/assets/db16ac53-c6b2-449e-8f54-4c61965fb84d)

When cache is hit then the response is in the right size:

![Image](https://github.com/user-attachments/assets/17b74bbc-0e76-44b2-8f68-5e1e4844f83b)

Here is my traefik route page with the cache:

![Image](https://github.com/user-attachments/assets/095a24ef-3a1f-40e1-881d-b30fc7a0313b)

This is the HTTPRoute object:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    argocd.argoproj.io/instance: stg-webapps-auth-app
  name: webapps-auth-app-insider-route
  namespace: rotate
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: webapps-auth-app
          port: 8443
          weight: 1
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replaceFullPath: /api/auth/verify
              type: ReplaceFullPath
        - extensionRef:
            group: traefik.io
            kind: Middleware
            name: webapps-auth-app-souin
          type: ExtensionRef
      matches:
        - path:
            type: Exact
            value: /webapps-auth/api/auth/verify-cache
```

This is the souin configuration:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  labels:
    argocd.argoproj.io/instance: stg-webapps-auth-app
  name: webapps-auth-app-souin
  namespace: rotate
spec:
  plugin:
    souin:
      api:
        basepath: /souin-api
        prometheus: {}
        souin:
          basepath: /souin
      default_cache:
        allowed_http_verbs:
          - GET
          - POST
        default_cache_control: public
        key:
          hash: true
          headers:
            - Authorization
          hide: true
        mode: strict
        ttl: 15s

```
