### ISSUE TITLE
Feature Request - Add ability to set TTL depending URL/Headers/Cookies

### ISSUE THREAD

**Issue by darkweak** [darkweak/souin#66]
We want to be able to define the cache TTL depending either one of URL, Headers or Cookies or every ones at the same time.
We could replace the `MatchedURL` object to another one, like `CacheKey` with the following structure 
```go
type CacheKey struct {
    type  string (eg."headers"|"cookies")
    regex string
}
```  
Or another one with a priority field
```go
type CacheKey struct {
    url      string (eg."/^.+$/")
    cookies  string (eg."/^.+$/")
    priority int
}
```

Then the YAML could be one of 
```yaml
cache_keys:
  - type: headers
    regex: '/^.+$/'
  - type: cookies
    regex: '/^.+$/'
  - type: headers
    regex: '/^[A-z]+$/'
```
```yaml
cache_keys:
  - cookies: '/^.+$/'
    priority: 1
  - url: '/^.+$/'
    priority: 40
  - url: '/nothing$/'
    cookies: '/^Auth.+$/'
    priority: 999
```
